openapi: 3.0.2
info:
  title: Test Spec
  version: '0'
paths: {}
components:
  schemas:
    Entity:
      type: object
      properties:
        id:
          type: string
        isEntity:
          type: boolean
