version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      # spring is used for tests
      - dependency-name: org.springframework:spring-context
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
