version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    rebase-strategy: auto
    ignore:
      - dependency-name: org.springframework:spring-context
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
