openapi: 3.0.2
info:
  title: Test Spec
  version: '0.6'
servers:
- url: http://localhost:8080
paths:
  /completable:
    get:
      operationId: completable
      tags:
      - response
      responses:
        204:
          description: Ok.
  /single:
    get:
      operationId: single
      tags:
      - response
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
  /maybe:
    get:
      operationId: maybe
      tags:
      - response
      parameters:
      - name: found
        in: query
        required: true
        schema:
          type: boolean
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
        404:
          description: Ok.
  /array:
    get:
      operationId: array
      tags:
      - response
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Model'
  /noContent:
    get:
      tags:
      - response
      responses:
        200:
          description: Ok but no content defined.
  /stream:
    get:
      operationId: stream
      tags:
      - response
      responses:
        200:
          description: Ok.
          content:
            application/x-json-stream:
              schema:
                $ref: '#/components/schemas/Model'
components:
  schemas:
    Model:
      type: object
      properties:
        string:
          type: string
