openapi: 3.0.2
info:
  title: Test Spec
  version: '0'
paths: {}
components:
  schemas:
    Property:
      type: object
      properties:
        type:
          type: string
          enum:
            - Property
      required:
        - type
        - value
      additionalProperties:
        oneOf:
          - $ref: '#/components/schemas/Property'
          - $ref: '#/components/schemas/Relationship'
    Relationship:
      type: object
      properties:
        type:
          type: string
          enum:
            - Relationship
        object:
          type: string
          format: uri
      required:
        - type
        - object
      additionalProperties:
        oneOf:
          - $ref: '#/components/schemas/Property'
          - $ref: '#/components/schemas/Relationship'
    Entity:
      type: object
      properties:
        id:
          type: string
          format: uri
      additionalProperties:
        oneOf:
          - $ref: '#/components/schemas/Property'
          - $ref: '#/components/schemas/Relationship'
