openapi: 3.0.2
info:
  title: Test Spec
  version: '0.6'
servers:
- url: http://localhost:8080
paths:
  /body:
    post:
      description: 'validate body'
      operationId: body
      tags:
      - validation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Model'
      responses:
        204:
          description: Ok.
        400:
          description: BadRequest.
  /bodyWithCollection:
    post:
      description: 'validate body'
      operationId: bodyWithCollection
      tags:
      - validation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelWithCollection'
      responses:
        204:
          description: Ok.
        400:
          description: BadRequest.
  /param/query:
    get:
      description: 'validate query param'
      operationId: queryParam
      parameters:
      - name: modelId
        in: query
        required: true
        schema:
          type: integer
          format: int32
          minimum: 1
          maximum: 2
      tags:
      - validation
      responses:
        200:
          description: Ok.
        400:
          description: BadRequest.
components:
  schemas:
    Embedded:
      type: object
      required:
      - name
      properties:
        name:
          type: string
    Model:
      type: object
      required:
      - name
      - embedded
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          maxLength: 5
        embedded:
          $ref: '#/components/schemas/Embedded'
    ModelWithCollection:
      type: object
      required:
      - list
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/Model'
