openapi: 3.0.2
info:
  title: Test Spec
  version: '0'
paths: {}
components:
  schemas:
    positionDefinition:
      description: A single position
      type: array
      minItems: 2
      maxItems: 2
      items:
        type: number
      additionalProperties: false
    positionArrayDefinition:
      description: An array of positions
      type: array
      items:
        $ref: '#/components/schemas/positionDefinition'
    linearRingDefinition:
      description: An array of four positions where the first equals the last
      allOf:
        - $ref: '#/components/schemas/positionArrayDefinition'
        - minItems: 4
    polygonDefinition:
      description: An array of linear rings
      type: array
      items:
        $ref: '#/components/schemas/linearRingDefinition'
    Polygon:
      type: object
      properties:
        type:
          type: string
          enum:
            - Polygon
        coordinates:
          $ref: '#/components/schemas/polygonDefinition'