openapi: 3.0.2
info:
  title: Test Spec
  version: '0'
paths:
  /mediatype/multiple-content-types:
    get:
      operationId: multipleContentTypes
      responses:
        default:
          description: Ok
          content:
            application/json:
              schema:
                type: string
            text/plain:
              schema:
                type: string
