when:
  event: [manual, pull_request, push]
  branch: main
  path: [.woodpecker/lint.yaml, renovate.json, "**/*.sh", "**/*.yaml", "**/*.md"]

steps:

  renovate:
    image: kokuwaio/renovate-config-validator:42
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, renovate.json]]

  yaml:
    image: kokuwaio/yamllint:v1.37.1
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, "**/*.yaml"]]

  markdown:
    image: kokuwaio/markdownlint:0.45.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, "**/*.md", .markdownlint.yaml]]

  shellcheck:
    image: kokuwaio/shellcheck:v0.11.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, "**/*.sh"]]
