openapi: 3.0.2
info:
  title: Test Spec
  version: '0.6'
servers:
- url: http://localhost:8080
paths:
  /query/multiple-lists:
    get:
      operationId: getMultipleLists
      parameters:
      - name: a
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
      - name: b
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
      tags:
      - query
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
  /query/type/date:
    get:
      operationId: getTypeDate
      parameters:
      - name: date
        in: query
        required: false
        schema:
          type: string
          format: date
      tags:
      - query
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
  /query/type/date-time:
    get:
      operationId: getTypeDateTime
      parameters:
      - name: date-time
        in: query
        required: false
        schema:
          type: string
          format: date-time
      tags:
      - query
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
  /query/type/number:
    get:
      operationId: getTypeNumber
      parameters:
      - name: number
        in: query
        required: false
        schema:
          type: number
      tags:
      - query
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
  /query/type/uuid:
    get:
      operationId: getUuid
      parameters:
      - name: number
        in: query
        required: false
        schema:
          type: string
          format: uuid
      tags:
      - query
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
components:
  schemas:
    Model:
      type: object
      properties:
        number: 
          type: number
        uuid:
          type: string
          format: uuid
        date:
          type: string
          format: date
        dateTime:
          type: string
          format: date-time
        a:
          type: array
          items:
            type: string
        b:
          type: array
          items:
            type: string
