name: Snapshot

"on":
  workflow_dispatch: {}
  push:
    branches: [main]
    paths-ignore: ['**.md']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven
          server-id: sonatype-nexus
          server-username: SERVER_USERNAME
          server-password: SERVER_PASSWORD
      - run: mvn -B dependency:go-offline
      - run: mvn -B deploy
        env:
          SERVER_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      - uses: dorny/test-reporter@v1.5.0
        if: failure()
        with:
          name: surefire
          path: '**/target/surefire-reports/*.xml'
          reporter: java-junit
          list-suites: failed
          list-tests: failed
          fail-on-error: false
